export const SAVE_SHIP_ADDRESS = "SAVE_SHIP_ADDRESS";
export const SAVE_USERINFO = "SAVE_USERINFO";
export const SAVE_CITY = "SAVE_CITY";
export const ADD_CART = "ADD_CART";
export const REMOVE_CART = "REMOVE_CART";
export const INIT_CART = "INIT_CART";

export default {
	SAVE_SHIP_ADDRESS,
	SAVE_USERINFO,
	SAVE_CITY,
	ADD_CART,
	REMOVE_CART,
	INIT_CART
}