name: sync-to-gitee
on: [push]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY 这个存私钥不带.pub那个文件里面的 gitee上 存储公钥 带.pub那个文件里面的
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: "git@github.com:linzowo/uniapp-elm.git"
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: "git@gitee.com:linzowo/uniapp-elm.git"

    - name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@master
      with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: linzowo
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库
          gitee-repo: linzowo/uniapp-elm
